const u = (n) => `/gallery-${n}.jpg`

export const initialProjects = [
  {
    id: 'p1',
    name: 'Lakeview Loft',
    address: '1420 Shoreline Dr, Chicago, IL',
    status: 'active',
    type: 'diy',
    views: 1284,
    leads: 23,
    publishedAt: 'Published 3 days ago',
    thumb: 'img1',
    photo: u(6),
  },
  {
    id: 'p2',
    name: 'Oak Hill Residence',
    address: '88 Oak Hill Rd, Austin, TX',
    status: 'active',
    type: 'pro',
    views: 642,
    leads: 11,
    publishedAt: 'Published last week',
    thumb: 'img2',
    photo: u(4),
  },
  {
    id: 'p3',
    name: 'Riverside Studio',
    address: '210 River St, Portland, OR',
    status: 'processing',
    type: 'diy',
    progress: 66,
    submittedAt: Date.now() - 1000 * 60 * 60 * 26,
    stage: 'processing',
    thumb: 'img3',
    photo: u(5),
  },
  {
    id: 'p4',
    name: 'Elm Street Bungalow',
    address: '77 Elm St, Denver, CO',
    status: 'pro-pending',
    type: 'pro',
    progress: 25,
    scheduledDate: '2026-04-19',
    stage: 'scheduled',
    thumb: 'img4',
    size: '1,200–2,000 sq ft',
  },
  {
    id: 'p5',
    name: 'Cedar Park Home',
    address: '412 Cedar Park Ave, Seattle, WA',
    status: 'draft',
    type: 'diy',
    progress: 33,
    steps: { scan: 'complete', pano: 'idle' },
    thumb: 'img1',
    photo: u(2),
  },
  {
    id: 'p6',
    name: 'Sunset Penthouse',
    address: '900 Pacific Ave, San Francisco, CA',
    status: 'active',
    type: 'pro',
    views: 2310,
    leads: 47,
    publishedAt: 'Published 5 days ago',
    thumb: 'img2',
    photo: u(1),
  },
  {
    id: 'p7',
    name: 'Maple Court Condo',
    address: '215 Maple Ct, Nashville, TN',
    status: 'active',
    type: 'diy',
    views: 389,
    leads: 8,
    publishedAt: 'Published 2 weeks ago',
    thumb: 'img3',
    photo: u(3),
  },
  {
    id: 'p8',
    name: 'Harbor View Loft',
    address: '42 Wharf Rd, Boston, MA',
    status: 'active',
    type: 'pro',
    views: 1055,
    leads: 19,
    publishedAt: 'Published last week',
    thumb: 'img1',
    photo: u(5),
  },
  {
    id: 'p9',
    name: 'Pine Ridge Cabin',
    address: '88 Pine Ridge Ln, Aspen, CO',
    status: 'active',
    type: 'diy',
    views: 756,
    leads: 14,
    publishedAt: 'Published 4 days ago',
    thumb: 'img4',
    photo: u(6),
  },
  {
    id: 'p10',
    name: 'Midtown Gallery',
    address: '330 W 42nd St, New York, NY',
    status: 'active',
    type: 'pro',
    views: 3102,
    leads: 61,
    publishedAt: 'Published 1 day ago',
    thumb: 'img2',
    photo: u(4),
  },
  {
    id: 'p11',
    name: 'Coral Springs Villa',
    address: '1200 Ocean Blvd, Miami, FL',
    status: 'active',
    type: 'pro',
    views: 1843,
    leads: 35,
    publishedAt: 'Published 6 days ago',
    thumb: 'img3',
    photo: u(2),
  },
  {
    id: 'p12',
    name: 'Silverlake Duplex',
    address: '745 Hyperion Ave, Los Angeles, CA',
    status: 'active',
    type: 'diy',
    views: 512,
    leads: 9,
    publishedAt: 'Published 3 weeks ago',
    thumb: 'img1',
    photo: u(1),
  },
]
